version: "3.8"

services:
  web:
    build: ./flask_app
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
    volumes:
      - ./flask_app:/usr/src/app
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
